# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_user_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='qwe123', max_length=100),
            preserve_default=False,
        ),
    ]
