# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20170622_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='profile',
            field=models.ForeignKey(default='mp', on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile'),
            preserve_default=False,
        ),
    ]
