# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.BooleanField(default=False)),
                ('tue', models.BooleanField(default=False)),
                ('wed', models.BooleanField(default=False)),
                ('thu', models.BooleanField(default=False)),
                ('fri', models.BooleanField(default=False)),
                ('sat', models.BooleanField(default=False)),
                ('sun', models.BooleanField(default=False)),
                ('weekly', models.BooleanField(default=False)),
                ('biweekly', models.BooleanField(default=False)),
                ('monthly', models.BooleanField(default=False)),
                ('daily', models.BooleanField(default=False)),
                ('once', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(verbose_name='date published')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Meal')),
            ],
        ),
    ]
