# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.CharField(default='UTC 0:00', max_length=100),
            preserve_default=False,
        ),
    ]
