# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170625_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='label',
            field=models.CharField(default='strict caloric diet', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.User'),
            preserve_default=False,
        ),
    ]
