# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sqlparse

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170630_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.User')),
            ],
        ),
##        migrations.RemoveField(
##            model_name='meal',
##            name='time',
##        ),
        migrations.RunSQL("INSERT INTO dashboard_meal_type (label, time, user_id, date_created) VALUES ('breakfast', 'UTC 8:00', 1, CURRENT_TIMESTAMP)"),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Meal_type', default=1)
        )
    ]
