# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170630_1934'),
    ]

    operations = [
    ]
